graph TD
  A[Paradigma Atual] --> B[Ciência Normal]
  B --> C[Anomalias]
  C --> D[Crescimento das anomalias]
  D --> E[Crise]
  E --> F[Revolução Científica]
  F --> G[Novo Paradigma]
  G --> H[Nova Ciência Normal]