graph TD
  A[Causas Estruturais] --> B[Crise Económica]
  A --> C[Reforma Agrária e Social]
  A --> D[Conflito Ideológico]
  D --> E[Nacionalistas]
  D --> F[Republicanos]
  E --> G[Franco]
  E --> H[Apoio Nazi-Fascista]
  F --> I[Azaña e La Pasionaria]
  F --> J[Brigadas Internacionais]